#
# https://www.linuxserver.io/blog/backup-your-data-to-b2-with-restic-and-backrest
#
---
services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}backrest/data:/data
      - ${LOCVOL1}backrest/config:/config
      - ${LOCVOL1}backrest/cache:/cache
      - ${LOCVOL1}backrest/tmp:/tmp
      - ${BACKUPSRC1}:/userdata # backup source
      - ${BACKUPDST}:/backupdst # local backup destination, usually /opt/backrest or /etc/backrest
    ports:
      - "9898:9898"
    restart: unless-stopped
#
#
#
networks:
  default:
    name: ${CONNET}
    external: true